### ISSUE TITLE
Allow upload of CollectionVersionSignatures via API

### ISSUE THREAD

**Issue by rochacbruno** [pulp/pulp_ansible#837]
**Is your feature request related to a problem? Please describe.**

To approve collections on automation hub it will be required that the collection has at least one valid signature attached to it, users will be able to upload a `namespace.collection-version.asc` file containing the ascii armoured detached signature file.

**Describe the solution you'd like**

An endpoint/viewset to enable upload of CollectionVersionSignature

```yaml
POST: https://pulp/pulp/api/v3/content/ansible/collection_signatures/
---
signature_file: path/to/namespace.collection-version.asc
signed_collection: reference to CollectionVersion being signed
repository:  name of the repository where that signature must be added
```

The content of the `namespace.collection-version.asc` must feed the `.data` attribute of the collection signature object.
signed_collection gets the relation with existing collection version on the same `repository` that is informed.

**validation**

The endpoint must have a `validate` method that on the default implementation can do a simple validation such as matching the artifact name `namespace.collection-version.asc` against `namespace.collection-version.tar.gz` or just ensuring the file isn't empty.

On galaxy_ng we are going to subclass this ViewSet/Serializer and on the validate we want to add a GPG verification process so we avoid upload of invalid signatures, we plan to do that via settings

e.g:

```py
GALAXY_VERIFICATION_KEYRING="/path/to/galaxy.kbx"
```

And then using GPG we are going to verify the signature + collection against the keys on that keyring, at this point I am not sure if this specific verification logic can go to pulp_ansible source or better to keep on galaxy side.

**Comment by gerrod3** [comment]
### Investigation into adding signature upload support
The current fields on the signature model include:
- signed_collection - the collection-version this signature points to
- data - the actual signature itself
- digest - the sha256 digest of the signature
- pubkey_fingerprint - the fingerprint of the public key used to create this signature
- signing_service - an optional signing service used to create this signature

The signature's uniqueness is determined by the `signed_collection` and `pubkey_fingerprint`, so these two pieces of information need to also be provided when uploading a signature.  Currently the signatures produced by the signing task use a collection-version's `MANIFEST.json` by passing it to the `signing_service` that the user supplies. The `signing_service` contains a user shell script that can use any cryptographic signature program to return a signature file.

### Some Key questions that arise from the current design:
1. Do we intend to only support(expect) OpenPGP signatures?
2. Do we care if the signatures are detached or encrypted?
3. What filename and format types should we expect?

### Option 1, No Convenience:
Have the user specify everything so that there is no confusion and no need for verification. Trust the user completely and if they make a mistake they will have to fix it themselves.
```yaml
POST: https://pulp/pulp/api/v3/content/ansible/collection_signatures/
---
signature_file: path/to/namespace.collection-version.asc (or any filename)
signed_collection: href to CollectionVersion being signed
pubkey_fingerprint: fingerprint of the pubkey used to create the signature
repository:  href of the repository where that signature must be added
```
### Option 2, Correct Filename:
Have the user specify the `signature_file`, `pubkey_fingerprint` and `repository`, but make sure the `signature_file` follows the format of `namespace.name-version.extension`. Since collection-versions have a global uniqueness constraint of namespace, name and version, we can easily validate if there is an existing collection-version for the signature to attach to.
```yaml
POST: https://pulp/pulp/api/v3/content/ansible/collection_signatures/
---
signature_file: path/to/namespace.collection-version.asc (any file-extension, but must be namespace.name-version)
pubkey_fingerprint: fingerprint of the pubkey used to create the signature
repository:  href of the repository where that signature must be added
```
### Option 3, Correct Filename + Assume OpenPGP:
If we assume the user will provide a signature from OpenPGP, then they will only have to provide the `signature_file` and `repository`. Use the same logic for the filename as the previous option, but now we can look inside the signature to find the `pubkey_fingerprint`. Note: if we have access to the system's keyring we could also verify that the signature is valid.
```yaml
POST: https://pulp/pulp/api/v3/content/ansible/collection_signatures/
---
signature_file: path/to/namespace.collection-version.asc (.asc or .sig file-extension, must be namespace.name-version)
repository:  href of the repository where that signature must be added
```
